export class SolicitudObject{
    constructor(
        categories: [],
        categoryName: string,
        category_id: number,
        created_date: string,
        date_required: string,
        descProf: string,
        description: string,
        hours_professional: string,
        hours_requestservice: string,
        img_profile: string,
        img_request: [],
        professional_profiles_id: number,
        request_id: number,
        status_id: number,
        status_name: string,
        status_order: string,
        supplierLastName: string,
        supplierName: string,
        supplier_id: number,
        ticket_number: number,
        user_client_id: number,
        work_days: string,
    ){};
}